# Generated by Django 4.2.3 on 2023-07-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_audio_file_audiorecord_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecord',
            old_name='audio',
            new_name='audio_file',
        ),
    ]
