# Generated by Django 4.2.3 on 2023-07-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_audio_audiorecord_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(unique=True)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
